on:
  push:
    branches: 
    - master
jobs:
  sync:
    runs-on: ubuntu-latest
    # Set GIT_SSH_COMMAND to accept new host keys
    env:
      GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=accept-new
    steps:
      - uses: actions/checkout@v7
        with:
          ref: master
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: |
          git remote add sync ${{ secrets.GIT_SYNC_REMOTE }}
          git remote update
          git push sync master
